language: node_js
node_js:
    - 14.7.0
script:
    - "npm run build"
    - "npm run test:nowatch"

before_deploy:
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.10.0

deploy:
  provider: heroku
  api_key: $HEROKU_TOKEN
  app: book-store-nik-web